# Generated by Django 6.0.4 on 2026-04-10 00:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Nombre de usuario')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('successful', models.BooleanField(default=False, verbose_name='Éxito')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
            ],
            options={
                'verbose_name': 'Intento de acceso',
                'verbose_name_plural': 'Intentos de acceso',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo institucional')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Teléfono')),
                ('access_level', models.PositiveSmallIntegerField(choices=[(1, 'Administración (Nivel 1)'), (2, 'Coordinador (Nivel 2)'), (3, 'Operativo (Nivel 3)'), (4, 'Externo (Nivel 4)')], db_index=True, default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Nivel de acceso')),
                ('role', models.CharField(blank=True, choices=[('Administrador IT', 'Administrador IT'), ('Coordinador Legal', 'Coordinador Legal'), ('Coordinador Humanitario', 'Coordinador Humanitario'), ('Operativo Humanitario', 'Operativo Humanitario'), ('Psicólogo', 'Psicólogo'), ('Comunicación', 'Comunicación'), ('Almacén', 'Almacén'), ('Personal Externo', 'Personal Externo')], max_length=64, verbose_name='Rol')),
                ('job_title', models.CharField(blank=True, max_length=128, verbose_name='Puesto')),
                ('onboarding_date', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso')),
                ('internal_id', models.CharField(blank=True, max_length=32, unique=True, verbose_name='Identificador interno')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='Acceso revocado')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revocación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado lógicamente')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('totp_secret', models.CharField(blank=True, max_length=64, verbose_name='TOTP secreto')),
                ('mfa_enabled', models.BooleanField(default=False, verbose_name='MFA activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_users', to=settings.AUTH_USER_MODEL, verbose_name='Revocado por')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborators', to='iam.area', verbose_name='Área')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=128, verbose_name='Acción')),
                ('details', models.TextField(blank=True, verbose_name='Detalles')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor_logs', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario objetivo')),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-created_at'],
            },
        ),
    ]
