# Generated by Django 6.0.4 on 2026-04-17 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_data', models.TextField(verbose_name='Datos del certificado encriptado')),
                ('fingerprint', models.CharField(max_length=64, unique=True, verbose_name='Huella digital')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('expires_at', models.DateTimeField(verbose_name='Fecha de expiración')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='Certificado revocado')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revocación')),
                ('collaborator', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificate', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_issued', to=settings.AUTH_USER_MODEL, verbose_name='Emitido por')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_revoked', to=settings.AUTH_USER_MODEL, verbose_name='Revocado por')),
            ],
            options={
                'verbose_name': 'Certificado de usuario',
                'verbose_name_plural': 'Certificados de usuario',
            },
        ),
    ]
