# Generated by Django 6.0.4 on 2026-04-17 19:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_usercertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='certificate_delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Certificado entregado'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='official_id_document',
            field=models.FileField(blank=True, null=True, upload_to='official_ids/', verbose_name='Identificación oficial'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='onboarding_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aprobado el'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='onboarding_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_onboardings', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='onboarding_requested_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Solicitado el'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collaborator',
            name='onboarding_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=16, verbose_name='Estado de onboarding'),
        ),
    ]
