"""
Django settings for casamonarca project.

Generated by 'django-admin startproject' using Django 6.0.4.
"""

import base64
import hashlib
import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-2p6xd2nr56uat=ax+n$duv9im5gx-3%6l7h$o8%-xc6@!pp6y2'
DEBUG = True
ALLOWED_HOSTS = ['localhost', '127.0.0.1']


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'iam',
    'registros',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'casamonarca.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'casamonarca.context_processors.workflow_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'casamonarca.wsgi.application'

MYSQL_DATABASE = os.environ.get('MYSQL_DATABASE')

if MYSQL_DATABASE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': MYSQL_DATABASE,
            'USER': os.environ.get('MYSQL_USER', 'casamonarca_user'),
            'PASSWORD': os.environ.get('MYSQL_PASSWORD', 'Cm2026MySQL!'),
            'HOST': os.environ.get('MYSQL_HOST', '127.0.0.1'),
            'PORT': os.environ.get('MYSQL_PORT', '3306'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'iam.Collaborator'
LOGIN_URL = 'iam:login'
LOGIN_REDIRECT_URL = 'iam:dashboard'

# --- Certificate Settings ---
CERT_ENCRYPTION_KEY = os.environ.get('CERT_ENCRYPTION_KEY')
if CERT_ENCRYPTION_KEY is None and DEBUG:
    derived_key = hashlib.sha256(SECRET_KEY.encode('utf-8')).digest()
    CERT_ENCRYPTION_KEY = base64.urlsafe_b64encode(derived_key).decode('utf-8')
# Generate a real key with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
CERT_ISSUER_NAME = os.environ.get('CERT_ISSUER_NAME', 'Casa Monarca IAM')
CERT_EXPIRATION_DAYS = int(os.environ.get('CERT_EXPIRATION_DAYS', '365'))
CERT_PRIVATE_KEY_PATH = os.environ.get('CERT_PRIVATE_KEY_PATH', '')

# --- ECC Signature Settings ---
# Path to the server's ECDSA private key (secp256k1).
# Auto-generated at BASE_DIR/ecc_signing_key.pem if not set.
ECC_PRIVATE_KEY_PATH = os.environ.get('ECC_PRIVATE_KEY_PATH', '')

if not DEBUG and CERT_ENCRYPTION_KEY is None:
    raise ImproperlyConfigured('CERT_ENCRYPTION_KEY must be set in production.')

LANGUAGE_CODE = 'es-mx'
TIME_ZONE = 'America/Mexico_City'
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
