# Generated by Django 5.2.14 on 2026-05-20 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrantRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('birth_date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('no_binario', 'No binario'), ('prefiero_no_decir', 'Prefiero no decir')], max_length=20, verbose_name='Género')),
                ('nationality', models.CharField(max_length=100, verbose_name='Nacionalidad')),
                ('country_of_origin', models.CharField(max_length=100, verbose_name='País de origen')),
                ('document_type', models.CharField(choices=[('pasaporte', 'Pasaporte'), ('id_nacional', 'Identificación nacional'), ('acta_nacimiento', 'Acta de nacimiento'), ('visa', 'Visa'), ('sin_documentos', 'Sin documentos'), ('otro', 'Otro')], max_length=30, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(blank=True, max_length=100, verbose_name='Número de documento')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('entry_date', models.DateField(verbose_name='Fecha de ingreso al país')),
                ('entry_point', models.CharField(max_length=200, verbose_name='Punto de ingreso')),
                ('transit_countries', models.TextField(blank=True, verbose_name='Países de tránsito')),
                ('intended_destination', models.CharField(blank=True, max_length=200, verbose_name='Destino final deseado')),
                ('marital_status', models.CharField(choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('union_libre', 'Unión libre'), ('divorciado', 'Divorciado/a'), ('viudo', 'Viudo/a')], max_length=20, verbose_name='Estado civil')),
                ('travels_alone', models.BooleanField(default=True, verbose_name='Viaja solo/a')),
                ('group_size', models.PositiveSmallIntegerField(default=1, verbose_name='Personas en el grupo')),
                ('minors_in_group', models.PositiveSmallIntegerField(default=0, verbose_name='Menores en el grupo')),
                ('assistance_requested', models.CharField(max_length=500, verbose_name='Tipo de asistencia solicitada')),
                ('migration_reason', models.TextField(verbose_name='Motivo de migración')),
                ('current_legal_status', models.CharField(choices=[('solicitante_asilo', 'Solicitante de asilo'), ('refugiado_reconocido', 'Refugiado reconocido'), ('migrante_regular', 'Migrante en situación regular'), ('migrante_irregular', 'Migrante en situación irregular'), ('desconoce', 'Desconoce su situación')], max_length=30, verbose_name='Situación migratoria actual')),
                ('shelter_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del albergue/alojamiento')),
                ('emergency_contact_name', models.CharField(max_length=255, verbose_name='Nombre del contacto de emergencia')),
                ('emergency_contact_phone', models.CharField(max_length=20, verbose_name='Teléfono del contacto de emergencia')),
                ('emergency_contact_relationship', models.CharField(max_length=100, verbose_name='Parentesco del contacto de emergencia')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones adicionales')),
                ('data_consent', models.BooleanField(default=False, verbose_name='Consentimiento de tratamiento de datos personales')),
                ('created_by_role', models.PositiveSmallIntegerField(verbose_name='Nivel de acceso del creador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
            ],
            options={
                'verbose_name': 'Registro migrante',
                'verbose_name_plural': 'Registros migrantes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MigrantRegistrationSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_hash', models.CharField(max_length=64, verbose_name='Hash SHA-256 del mensaje')),
                ('signature_r', models.TextField(verbose_name='Componente R de la firma ECDSA')),
                ('signature_s', models.TextField(verbose_name='Componente S de la firma ECDSA')),
                ('public_key', models.TextField(verbose_name='Clave pública (PEM)')),
                ('curve_name', models.CharField(max_length=50, verbose_name='Curva elíptica')),
                ('signed_by_role', models.PositiveSmallIntegerField(verbose_name='Nivel de acceso del firmante')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de firma')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='signature', to='registros.migrantregistration', verbose_name='Registro')),
                ('signed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures_made', to=settings.AUTH_USER_MODEL, verbose_name='Firmado por')),
            ],
            options={
                'verbose_name': 'Firma digital',
                'verbose_name_plural': 'Firmas digitales',
            },
        ),
    ]
