# Generated by Django 5.2.14 on 2026-05-27 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='migrantregistration',
            name='privacy_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Consentimiento aceptado el'),
        ),
        migrations.AddField(
            model_name='migrantregistration',
            name='privacy_accepted_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de aceptación'),
        ),
        migrations.AddField(
            model_name='migrantregistration',
            name='privacy_notice_version',
            field=models.CharField(default='1.0', max_length=10, verbose_name='Versión del aviso de privacidad'),
        ),
        migrations.CreateModel(
            name='BatchSignSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='Firmado el')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('item_count', models.PositiveIntegerField(verbose_name='Número de elementos firmados')),
                ('batch_root_hash', models.CharField(max_length=64, verbose_name='Hash raíz del lote')),
                ('signed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Sesión de firma masiva',
                'verbose_name_plural': 'Sesiones de firma masiva',
            },
        ),
        migrations.CreateModel(
            name='ActionSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('registration', 'Registro migrante'), ('workflow_step', 'Paso de aprobación'), ('arco_request', 'Solicitud ARCO'), ('batch_item', 'Elemento de firma masiva')], max_length=20, verbose_name='Tipo de sujeto')),
                ('subject_id', models.PositiveIntegerField(verbose_name='ID del sujeto')),
                ('message_hash', models.CharField(max_length=64, verbose_name='Hash del payload')),
                ('signature_r', models.TextField(verbose_name='Firma R')),
                ('signature_s', models.TextField(verbose_name='Firma S')),
                ('public_key', models.TextField(verbose_name='Clave pública (PEM)')),
                ('curve_name', models.CharField(default='secp256k1', max_length=50, verbose_name='Curva')),
                ('prev_chain_hash', models.CharField(blank=True, max_length=64, verbose_name='Hash del eslabón anterior')),
                ('chain_position', models.PositiveIntegerField(default=0, verbose_name='Posición en la cadena')),
                ('signed_by_role', models.PositiveSmallIntegerField(verbose_name='Nivel del firmante')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='Firmado el')),
                ('signed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_signatures', to=settings.AUTH_USER_MODEL, verbose_name='Firmado por')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='registros.batchsignsession', verbose_name='Sesión de firma masiva')),
            ],
            options={
                'verbose_name': 'Firma de acción',
                'verbose_name_plural': 'Firmas de acciones',
                'ordering': ['chain_position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('update_registration', 'Actualizar Registro'), ('delete_registration', 'Eliminar Registro'), ('arco_access', 'ARCO — Acceso'), ('arco_rectification', 'ARCO — Rectificación'), ('arco_cancellation', 'ARCO — Cancelación'), ('arco_opposition', 'ARCO — Oposición')], max_length=30, verbose_name='Tipo de acción')),
                ('state', models.CharField(choices=[('submitted', 'Enviado'), ('pending_review', 'En revisión'), ('escalated', 'Escalado al nivel superior'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('signed', 'Firmado digitalmente'), ('executed', 'Ejecutado')], db_index=True, default='submitted', max_length=20, verbose_name='Estado')),
                ('requested_by_role', models.PositiveSmallIntegerField(verbose_name='Nivel del solicitante')),
                ('payload', models.JSONField(default=dict, verbose_name='Datos de la solicitud')),
                ('notes', models.TextField(blank=True, verbose_name='Notas del solicitante')),
                ('current_approver_level', models.PositiveSmallIntegerField(verbose_name='Nivel aprobador actual')),
                ('pending_levels', models.JSONField(default=list, verbose_name='Niveles pendientes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('action_signature', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_request', to='registros.actionsignature', verbose_name='Firma de acción')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_requests', to='registros.migrantregistration', verbose_name='Registro afectado')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Solicitud de flujo',
                'verbose_name_plural': 'Solicitudes de flujo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArcoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arco_type', models.CharField(choices=[('access', 'Acceso — conocer los datos almacenados'), ('rectification', 'Rectificación — corregir datos inexactos'), ('cancellation', 'Cancelación — solicitar eliminación de datos'), ('opposition', 'Oposición — oponerse a un uso específico')], max_length=20, verbose_name='Tipo de derecho ARCO')),
                ('state', models.CharField(choices=[('submitted', 'Enviada'), ('in_review', 'En revisión'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('executed', 'Ejecutada'), ('escalated', 'Escalada')], db_index=True, default='submitted', max_length=20, verbose_name='Estado')),
                ('description', models.TextField(verbose_name='Descripción de la solicitud')),
                ('execution_notes', models.TextField(blank=True, verbose_name='Notas de ejecución')),
                ('legal_deadline', models.DateField(blank=True, help_text='20 días hábiles desde la recepción.', null=True, verbose_name='Plazo legal de respuesta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Recibida el')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Revisada el')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ejecutada el')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arco_requests_executed', to=settings.AUTH_USER_MODEL, verbose_name='Ejecutado por')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arco_requests', to='registros.migrantregistration', verbose_name='Registro afectado')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arco_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arco_requests_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('workflow_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arco_request', to='registros.workflowrequest', verbose_name='Flujo de aprobación')),
            ],
            options={
                'verbose_name': 'Solicitud ARCO',
                'verbose_name_plural': 'Solicitudes ARCO',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('escalated', 'Escalado')], max_length=20, verbose_name='Decisión')),
                ('actor_role', models.PositiveSmallIntegerField(verbose_name='Nivel del actor')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('step_hash', models.CharField(blank=True, max_length=64, verbose_name='Hash de este paso')),
                ('prev_step_hash', models.CharField(blank=True, max_length=64, verbose_name='Hash del paso anterior')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_steps', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_steps', to='registros.workflowrequest', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Paso de aprobación',
                'verbose_name_plural': 'Pasos de aprobación',
                'ordering': ['created_at'],
            },
        ),
    ]
