# Generated by Django 5.2.14 on 2026-05-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrantregistration',
            name='folio',
            field=models.CharField(blank=True, max_length=32, unique=True, verbose_name='Folio'),
        ),
    ]
