# Generated by Django 5.2.14 on 2026-06-01 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_add_internal_id'),
        ('registros', '0004_migrantregistration_folio'),
    ]

    operations = [
    ]
