# Generated by Django 5.2.14 on 2026-06-01 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_merge_20260601_1540'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='migrantregistration',
            name='folio',
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=20, unique=True, verbose_name='ID de caso')),
                ('rol_display', models.CharField(max_length=30, verbose_name='Rol del solicitante')),
                ('summary', models.CharField(max_length=255, verbose_name='Resumen corto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('priority', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En proceso'), ('cerrado', 'Cerrado')], default='abierto', max_length=15, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_created', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='registros.migrantregistration', verbose_name='Registro migrante')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
