# Generated by Django 5.2.13 on 2026-06-02 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='workflow_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket', to='registros.workflowrequest', verbose_name='Solicitud de workflow'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='registration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='registros.migrantregistration', verbose_name='Registro migrante'),
        ),
        migrations.AlterField(
            model_name='workflowrequest',
            name='action_type',
            field=models.CharField(choices=[('update_registration', 'Actualizar Registro'), ('delete_registration', 'Eliminar Registro'), ('create_registration', 'Crear Registro'), ('arco_access', 'ARCO — Acceso'), ('arco_rectification', 'ARCO — Rectificación'), ('arco_cancellation', 'ARCO — Cancelación'), ('arco_opposition', 'ARCO — Oposición')], max_length=30, verbose_name='Tipo de acción'),
        ),
    ]
