# Generated by Django 5.2.14 on 2026-06-02 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0007_ticket_workflow_request_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcorequest',
            name='action_signature',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arco_request_closure', to='registros.actionsignature', verbose_name='Firma de cierre'),
        ),
        migrations.AddField(
            model_name='arcorequest',
            name='attached_document',
            field=models.FileField(blank=True, null=True, upload_to='arco_docs/', verbose_name='Documento adjunto (PDF)'),
        ),
        migrations.AddField(
            model_name='arcorequest',
            name='case_id',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='ID de caso ARCO'),
        ),
        migrations.AddField(
            model_name='arcorequest',
            name='generated_document',
            field=models.FileField(blank=True, null=True, upload_to='arco_exports/', verbose_name='Documento generado (PDF de Acceso)'),
        ),
        migrations.AddField(
            model_name='arcorequest',
            name='ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arco_request', to='registros.ticket', verbose_name='Ticket de caso'),
        ),
    ]
