# Generated by Django 5.2.14 on 2026-06-02 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0008_arco_case_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='migrantregistration',
            name='consent_by_proxy',
            field=models.BooleanField(default=False, help_text='Marcar cuando el personal captura el consentimiento presencialmente en nombre del beneficiario.', verbose_name='Capturado por personal en nombre del beneficiario'),
        ),
        migrations.AddField(
            model_name='migrantregistration',
            name='consent_method',
            field=models.CharField(choices=[('digital', 'Digital (este formulario)'), ('verbal', 'Verbal con testigo'), ('written', 'Firmado en papel')], default='digital', max_length=10, verbose_name='Método de captura del consentimiento'),
        ),
        migrations.CreateModel(
            name='RegistrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('view', 'Consulta'), ('create', 'Creación'), ('update', 'Modificación'), ('delete', 'Eliminación'), ('consent', 'Consentimiento registrado'), ('arco_created', 'Solicitud ARCO recibida'), ('arco_reviewed', 'Solicitud ARCO en revisión'), ('arco_executed', 'Solicitud ARCO ejecutada'), ('export', 'Exportación de datos'), ('workflow_created', 'Solicitud de flujo creada'), ('workflow_approved', 'Solicitud de flujo aprobada'), ('workflow_rejected', 'Solicitud de flujo rechazada'), ('workflow_executed', 'Solicitud de flujo ejecutada')], db_index=True, max_length=24, verbose_name='Tipo de evento')),
                ('actor_role', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nivel del actor')),
                ('details', models.TextField(blank=True, verbose_name='Detalles')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y hora')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_events', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='registros.migrantregistration', verbose_name='Registro')),
            ],
            options={
                'verbose_name': 'Evento de expediente',
                'verbose_name_plural': 'Eventos de expediente',
                'ordering': ['created_at'],
            },
        ),
    ]
