# Generated by Django 6.0.4 on 2026-06-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0009_migrantregistration_consent_by_proxy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignedFlowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('accept_user_registration', 'Aceptar registro de usuario'), ('reject_user_registration', 'Rechazar registro de usuario'), ('delete_record', 'Eliminar registro (soft delete)'), ('process_arco_access', 'Procesar ARCO — Acceso'), ('process_arco_rectification', 'Procesar ARCO — Rectificación'), ('process_arco_cancellation', 'Procesar ARCO — Cancelación'), ('process_arco_opposition', 'Procesar ARCO — Oposición'), ('authorize_document', 'Autorizar documento'), ('revoke_user_access', 'Revocar acceso de colaborador')], max_length=40, verbose_name='Acción')),
                ('log_data_json', models.TextField(verbose_name='JSON canónico del log')),
                ('signature_b64', models.TextField(verbose_name='Firma digital base64')),
                ('cert_fingerprint', models.CharField(max_length=64, verbose_name='Fingerprint del certificado')),
                ('signer_user_id', models.PositiveIntegerField(verbose_name='ID del firmante')),
                ('target_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del objetivo')),
                ('target_type', models.CharField(blank=True, max_length=64, verbose_name='Tipo del objetivo')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='Firmado el')),
                ('is_verified', models.BooleanField(default=True, verbose_name='Firma verificada al crear')),
            ],
            options={
                'verbose_name': 'Log de flujo final firmado',
                'verbose_name_plural': 'Logs de flujos finales firmados',
                'ordering': ['-signed_at'],
            },
        ),
    ]
