# Generated by Django 5.2.14 on 2026-06-03 06:24

import crypto_core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0013_arco_cancel_and_wf_mods'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrantregistration',
            name='first_name',
            field=crypto_core.fields.EncryptedTextField(verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='migrantregistration',
            name='first_surname',
            field=crypto_core.fields.EncryptedTextField(verbose_name='Primer apellido'),
        ),
        migrations.AlterField(
            model_name='migrantregistration',
            name='state_or_region',
            field=models.CharField(max_length=100, verbose_name='Departamento/Estado'),
        ),
        migrations.AlterField(
            model_name='registrationevent',
            name='event_type',
            field=models.CharField(choices=[('view', 'Consulta'), ('create', 'Creación'), ('update', 'Modificación'), ('delete', 'Eliminación'), ('consent', 'Consentimiento registrado'), ('arco_created', 'Solicitud ARCO recibida'), ('arco_reviewed', 'Solicitud ARCO en revisión'), ('arco_executed', 'Solicitud ARCO ejecutada'), ('export', 'Exportación de datos'), ('workflow_created', 'Solicitud de flujo creada'), ('workflow_approved', 'Solicitud de flujo aprobada'), ('workflow_rejected', 'Solicitud de flujo rechazada'), ('workflow_executed', 'Solicitud de flujo ejecutada'), ('approved_with_changes', 'Aprobado con cambios por ejecutor')], db_index=True, max_length=24, verbose_name='Tipo de evento'),
        ),
        migrations.CreateModel(
            name='ArcoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='ID de ticket ARCO')),
                ('state', models.CharField(choices=[('submitted', 'Enviada'), ('coordinator_review', 'En revisión (Coordinador)'), ('escalated', 'Escalada a Administración'), ('admin_approval', 'Esperando aprobación de Admin'), ('executed', 'Ejecutada'), ('rejected', 'Rechazada')], db_index=True, default='submitted', max_length=25, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('coordinator_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Revisado por Coordinador el')),
                ('coordinator_notes', models.TextField(blank=True, verbose_name='Notas del Coordinador')),
                ('admin_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprobado por Admin el')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas del Admin')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ejecutada el')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Motivo del rechazo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('admin_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arco_tickets_admin_approved', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por Admin')),
                ('admin_signature', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arco_ticket_admin_signature', to='registros.actionsignature', verbose_name='Firma Digital del Admin')),
                ('arco_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arco_ticket', to='registros.arcorequest', verbose_name='Solicitud ARCO asociada')),
                ('coordinator_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arco_tickets_coordinator_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por Coordinador')),
                ('coordinator_signature', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arco_ticket_coordinator_auth', to='registros.actionsignature', verbose_name='Autenticación del Coordinador')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arco_tickets_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Ticket ARCO',
                'verbose_name_plural': 'Tickets ARCO',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['state', 'created_at'], name='registros_a_state_1c5b15_idx'), models.Index(fields=['created_by', 'state'], name='registros_a_created_86123f_idx')],
            },
        ),
    ]
